package:
  name: slacker
  version: "0.9.0"

source:
  fn: slacker-0.9.0.tar.gz
  url: https://pypi.python.org/packages/source/s/slacker/slacker-0.9.0.tar.gz
  md5: b4e1aad10eadc90dd53fcbf38e169965
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - slacker = slacker:main
    #
    # Would create an entry point called slacker that calls slacker.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.2.1

  run:
    - python
    - requests >=2.2.1

test:
  # Python imports
  imports:
    - slacker

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/os/slacker/
  license: Apache Software License
  summary: 'Slack API client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
