package:
  name: gnumpy
  version: "0.2"

source:
  fn: gnumpy-0.2.tar.gz
  url: https://pypi.python.org/packages/source/g/gnumpy/gnumpy-0.2.tar.gz
  md5: 285c5c1c110a0a3f0ab10a2274bd08b7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gnumpy = gnumpy:main
    #
    # Would create an entry point called gnumpy that calls gnumpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.cs.toronto.edu/~tijmen/gnumpy.html
  license: BSD-derived (see LICENSE.txt)
  summary: "Gnumpy is a simple Python module that interfaces in a way almost identical to numpy, but does its computations on your computer's  GPU, using Cudamat."

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
