package:
  name: twython
  version: "3.3.0"

source:
  fn: twython-3.3.0.tar.gz
  url: https://pypi.python.org/packages/source/t/twython/twython-3.3.0.tar.gz
  md5: 0888d3064d4379035eb20d1dfa0ab334
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - twython = twython:main
    #
    # Would create an entry point called twython that calls twython.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.1.0
    - requests_oauthlib >=0.4.0

  run:
    - python
    - requests >=2.1.0
    - requests_oauthlib >=0.4.0

test:
  # Python imports
  imports:
    - twython
    - twython.streaming

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ryanmcgrath/twython/tree/master
  license: MIT License
  summary: 'Actively maintained, pure Python wrapper for the     Twitter API. Supports both normal and streaming Twitter APIs'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
