package:
  name: joblib
  version: "0.9.3"

source:
  fn: joblib-0.9.3.tar.gz
  url: https://pypi.python.org/packages/source/j/joblib/joblib-0.9.4.tar.gz
  md5: 31d29b22fcf00cd1a1358828ba67376f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - joblib = joblib:main
    #
    # Would create an entry point called joblib that calls joblib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - nose

  run:
    - python

test:
  # Python imports
  imports:
    - joblib
    - joblib.test
    - joblib.test.data

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # Put any additional test requirements here.
  requires:
    - nose

about:
  home: http://pythonhosted.org/joblib/
  license: BSD License
  summary: '\nLightweight pipelining: using Python functions as pipeline jobs.\n'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
